import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconFolder,
  IconUsers,
  IconCrown,
  IconStar,
  IconBox,
  IconCalendar,
  IconChecklist,
  IconBook,
  IconMap,
  IconHeart,
  IconFileDescription,
  IconWand,
  IconChartBar,
  IconPigMoney,
  IconRepeat,
  IconTarget,
  IconWallet,
  IconActivity,
  IconHome,
  IconTool,
  IconCode,
  IconFlame,
  IconShoppingCart,
  IconAddressBook,
  IconGift
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconBox,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  workspace: IconFolder,
  teams: IconUsers,
  pro: IconCrown,
  exclusive: IconStar,
  account: IconUserCircle,
  profile: IconUser,
  // Nuevos iconos para módulos
  finance: IconPigMoney,
  productivity: IconChecklist,
  learning: IconBook,
  travel: IconMap,
  wellness: IconHeart,
  documents: IconFileDescription,
  automations: IconWand,
  reports: IconChartBar,
  recurring: IconRepeat,
  goals: IconTarget,
  accounts: IconWallet,
  calendar: IconCalendar,
  tasks: IconChecklist,
  health: IconActivity,
  // Módulos adicionales
  home: IconHome,
  maintenance: IconTool,
  projects: IconCode,
  habits: IconFlame,
  shopping: IconShoppingCart,
  contacts: IconAddressBook,
  events: IconGift
};
